if (APPLE)
	include(${CMAKE_PLATFORM_PATH}/osx/platform.cmake)
elseif (UNIX)
	include(${CMAKE_PLATFORM_PATH}/unix/platform.cmake)
elseif (WIN32)
	include(${CMAKE_PLATFORM_PATH}/windows/platform.cmake)
endif ()